### PR TITLE
Implement trectext format

### LINKED ISSUE #2: Trectext
We need to support `trecweb` and `trectext`. Currently we support the former, do we want to add the latter in here too?

### PR DESCRIPTION
**Pull request by elshize**
Fixes #2

### CODE REVIEW

**Comment by amallia** [comment]
```
amallia@xor:~$ zcat /data/wapo-all.trec.v2.txt.gz |grep -o  "<\w*>"  | sort |uniq
<b>
<br>
<del>
<DOC>
<DOCNO>
<em>
<HEADLINE>
<i>
<TEXT>
<TITLE>
<URL>
```


It seems to be important to index `HEADLINE` and `TITLE`. Also it looks like there is some non stripped HTML content

**Comment by amallia** [comment]
So, I have done some research and I think we can take `URL` for granted. It should appear right after `DOCNO`.
After that we can have 1 or more additional fields (`TITLE`, `HEADLINE`, `TEXT`)

```
<DOC>
<DOCNO> b2e89334-33f9-11e1-825f-dabc29fd7071 </DOCNO>
<URL> https://www.washingtonpost.com/sports/colleges/danny-coale-jarrett-boykin-are-a-perfect-1-2-punch-for-virginia-tech/2011/12/31/gIQAAaW4SP_story.html </URL>
<TITLE> Danny Coale, Jarrett Boykin are a perfect 1-2 punch for Virginia Tech </TITLE>
<HEADLINE> Virginia Tech wide receiver Danny Coale (19) was lightly recruited out of Episcopal in Alexandria but has teamed with Jarrett Boykin for a record-breaking receiving duo. (John Bazemore/AP) </HEADLINE>
<TEXT>
stuff here...
</TEXT>
``` 


EDIT: `URL` is not always present... For example, it seems that Robust04 does not have a URL field. Question is, what do we consider to be the URL then?

**Comment by JMMackenzie** [comment]
> EDIT: `URL` is not always present... For example, it seems that Robust04 does not have a URL field. Question is, what do we consider to be the URL then?

I think we can just ignore it, right? It could certainly be true that we index documents that don't have associated webpages in the future.

**Comment by elshize** [comment]
@amallia see my latest commit.

I agree with @JMMackenzie, a URL is not a requirement for a document in a search engine. This means sometimes we might not be able to sort by URLs for performance but that's not a deal breaker.

The bottom line is: if a URL is missing, there's nothing we can do about it. And since we have a URL field in a record, I decided to just leave it blank if missing. We could go an make it more semantically correct and use an optional but that's an overkill at this point.

**Review by amallia — APPROVED** [review]

**Pull request merged**
